# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.network "private_network", ip: "172.16.10.101"
    config.vm.hostname = "worker1.nth"
  
    config.vm.provider "virtualbox" do |vb|
       vb.name = "worker1.nth"
       vb.cpus = 1
       vb.memory = "1024"
    end
     
    config.vm.provision "shell", path: "./../install-docker-kube.sh"
  
    config.vm.provision "shell", inline: <<-SHELL
    
      echo "root password"
      echo "123" | passwd --stdin root
      sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
      systemctl reload sshd
  
  
  cat >>/etc/hosts<<EOF
  172.16.10.100 master.nth
  172.16.10.101 worker1.nth
  172.16.10.102 worker2.nth
  EOF
  
      
    SHELL
  end