apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo1
  name: mongo1
spec:
  ports:
    - name: "27021"
      port: 27021
      targetPort: 27017
  selector:
    io.kompose.service: mongo1
status:
  loadBalancer: {}
