apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo3
  name: mongo3
spec:
  ports:
    - name: "27023"
      port: 27023
      targetPort: 27017
  selector:
    io.kompose.service: mongo3
status:
  loadBalancer: {}
