apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo2
  name: mongo2
spec:
  ports:
    - name: "27022"
      port: 27022
      targetPort: 27017
  selector:
    io.kompose.service: mongo2
status:
  loadBalancer: {}
