apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo3
  name: mongo3
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo3
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/convercompose-mongors-network: "true"
        io.kompose.service: mongo3
    spec:
      containers:
        - command:
            - /usr/bin/mongod
            - --bind_ip_all
            - --replSet
            - dbrs
          image: mongo:4.4
          name: mongo3
          ports:
            - containerPort: 27017
              hostPort: 27023
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: mongo3-claim0
      restartPolicy: Always
      volumes:
        - name: mongo3-claim0
          persistentVolumeClaim:
            claimName: mongo3-claim0
status: {}
